In [117]:
import os
import hashlib

In [119]:
def hash_file(filename):
    h = hashlib.sha1()
    with open(filename,'rb') as file:
        chunk = 0
        while chunk != b'':
            chunk = file.read(1024)
            h.update(chunk)
        # return the hex representation of digest
        return h.hexdigest()
    
    
hash_set = set()

# assign directory
directory = 'C:/Users/bhasingh/OneDrive - ALLEGIS GROUP/Desktop/Python_Data'
 
# iterate over files in
# that directory
for root, dirs, files in os.walk(directory):
    for filename in files:
        filePath = os.path.join(root, filename)
        if hash_file(filePath) in hash_set:
                print("The Duplicate file removed:", filePath)
                os.remove(filePath)
        else:
                hash_set.add(hash_file(filePath))
                
print(hash_set)

The Duplicate file removed: C:/Users/bhasingh/OneDrive - ALLEGIS GROUP/Desktop/Python_Data\2march_Assignment2 - Copy.docx
{'92d4c3097ac6236bcff9cad3e296175f9b7c4f6b', '717c57fb427a7350a5fa49ec7338b520dfb9aec3', '81aee750418a1d21b51bf0ca51e91360883743d6', 'fa2183d05eef875e8cc584e6fb87db9c618164b4', 'bc2d29c021b56ea360052892f596dc9fd958980a', '6c233348968dec893ebff294cc472da8393171db', 'dd9aaa6cd0b54c56988dfaf6f21dd5e2423a792d', '6905ee7569875664938f8b876048f65b6cdb602e', '7ea7b9a91eaf4a7cff199d302b587afbb89c1dd9', 'dfda8ff2cd124f184113f271b4fcd2b629da687f', '9f5de5d208664c71870a7f13051b2f6617d6c231'}


In [57]:
import random
import string

lc = 2
dc = 2

password = '' 

password += random.choice(string.ascii_uppercase)
while lc > 0:
    password += random.choice(string.ascii_lowercase)
    lc = lc - 1
while dc > 0:
    password += str(random.randint(0,9))
    dc = dc - 1
password += str(random.choice(string.punctuation))

str_var = list(password)
random.shuffle(str_var)
print(''.join(str_var))

O<pk28


In [2]:
import numpy as np

rows = int(input('Enter the number of rows: '))
columns = int(input('Enter the number of columns: '))

elements = rows*columns

cube_arr = np.arange(0,elements).reshape(rows,columns)

cube_list = []
for i in range(0,rows):
    cube_list.append(list(cube_arr[i]))
    
count = 0
for i in range(0,rows):
    for j in range(0,columns):
        if count!=0 or count!=1:
            if count == 2:
                cube_list[i][j] = cube_list[i][j] ** 3
                count += 1
                continue
            prime = cube_list[i][j]
            cp = 0 
            for n in range(2,prime):
                if prime%n == 0 :
                    cp += 1
            if cp == 0:
                cube_list[i][j] = cube_list[i][j] ** 3
        count += 1
                
print(np.array(cube_list))

Enter the number of rows: 5
Enter the number of columns: 6
[[    0     1     8    27     4   125]
 [    6   343     8     9    10  1331]
 [   12  2197    14    15    16  4913]
 [   18  6859    20    21    22 12167]
 [   24    25    26    27    28 24389]]


In [3]:
import numpy as np

rows = int(input('Enter the number of rows: '))
columns = int(input('Enter the number of columns: '))

elements = rows*columns

cube_arr = np.arange(0,elements).reshape(rows,columns)

cube_list = []
for i in range(0,rows):
    cube_list.append(list(cube_arr[i]))
    
count = 0
prev_ele = 0
for i in range(0,rows):
    for j in range(0,columns):
        if count!=0 or count!=1:
            if count == 2:
                cube_list[i][j] = cube_list[i][j] ** 3
                count += 1
                continue
            prime = cube_list[i][j]
            cp = 0 
            for n in range(2,prime):
                if prime%n == 0 :
                    cp += 1
            if cp == 0:
                cube_list[i][j] = cube_list[i][j] ** 3 + prev_ele
        count += 1
        prev_ele  = cube_list[i][j] 
                
print(np.array(cube_list))

Enter the number of rows: 6
Enter the number of columns: 7
[[    0     1     8    28     4   129     6]
 [  349     8     9    10  1341    12  2209]
 [   14    15    16  4929    18  6877    20]
 [   21    22 12189    24    25    26    27]
 [   28 24417    30 29821    32    33    34]
 [   35    36 50689    38    39    40 68961]]


In [6]:
arr1 = np.array([1, 3, 4, 5, 7])
arr2 = np.array([2, 3, 5, 6])

print(np.intersect1d(arr1, arr2))

[3 5]


In [31]:
r=int(input("Enter the row number: "))
c=int(input("Enter the column number: "))
arr_7 = np.array([[(i*c+j)*7 for j in range(c)] for i in range(r)])
print(arr_7)
print('The last element in the array: ', arr_7[-1][-1])

Enter the row number: 7
Enter the column number: 7
[[  0   7  14  21  28  35  42]
 [ 49  56  63  70  77  84  91]
 [ 98 105 112 119 126 133 140]
 [147 154 161 168 175 182 189]
 [196 203 210 217 224 231 238]
 [245 252 259 266 273 280 287]
 [294 301 308 315 322 329 336]]
The last element in the array:  336


In [34]:
#CheckerBoard
import numpy as np

r=int(input("Enter the row number: "))
c=int(input("Enter the column number: "))
arr2 = np.ones((r,c), dtype = 'int8')

for i in range(r):
    for j in range(c):
        if (i+j)%2 != 0:
            arr2[i][j] = 0
print(arr2)

Enter the row number: 5
Enter the column number: 7
[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


In [66]:
arr5 =np.array([chr(i) for i in range(65,89)]).reshape(6,4)
vowel = {'a','e','i','o','u'}
print(arr5)

arr5[-1][-1] = 'O'
arr5[2][1] = 'a'
arr5[3][2] = 'o'
arr5[-1][1] = '0'

print('\n',arr5)

list1 = []
for i in range(6):
        list1.append(list(arr5[i]))

c = 0
for i in range(6):
    for j in range(4):
        if list1[i][j].lower() in vowel:
            list1[i][j] = np.nan
            c += 1

arrfin = np.empty((6,4), dtype='str')
for i in range(6):
    arrfin[i] = np.array(list1[i])
print('\n')
print(arrfin)

print('The number of missing values: ',c)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']
 ['I' 'J' 'K' 'L']
 ['M' 'N' 'O' 'P']
 ['Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X']]

 [['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']
 ['I' 'a' 'K' 'L']
 ['M' 'N' 'o' 'P']
 ['Q' 'R' 'S' 'T']
 ['U' '0' 'W' 'O']]


[['n' 'B' 'C' 'D']
 ['n' 'F' 'G' 'H']
 ['n' 'n' 'K' 'L']
 ['M' 'N' 'n' 'P']
 ['Q' 'R' 'S' 'T']
 ['n' '0' 'W' 'n']]
The number of missing values:  7
